### ISSUE TITLE
`hm_iter` is difficult to use in a thread-safe manner or in single-threaded cases where reentry is possible

### ISSUE THREAD

**Issue by rpetrich** [e-dant/salmagundi#1]
Adding an extra "info" parameter that `hm_iter` passes into the iterator callback makes it possible to use hm_iter in many more scenarios. Without this, the caller has to resort to passing data that the iterator callback might need via a thread-local variable or some other out of band mechanism.

**Comment by e-dant** [comment]
This was leftover; I removed this in favor of just letting folks iterate the map's .items normally. 

The declaration should be removed. The implementation is.
