### ISSUE TITLE
Include a License File

### ISSUE THREAD

**Issue by rblath** [e-dant/salmagundi#9]
It would be nice to have a clear license for your code. The only one I found is in [include/rapidhash.h](https://github.com/e-dant/salmagundi/blob/f4deeeac971b2ff6edd4561a3c4775fdd3e58f68/include/rapidhash.h#L7). Is your code also licensed as BSD-2 ?
Thanks.

**Comment by e-dant** [comment]
MIT OR Apache-2.0 for the salmagundi stuff (because that's what the rest of my projects almost always use, and seems to be the default for small foss projects elsewhere). 

Added license files and spdx magic comments.
